#!/bin/bash
#create directory

#outputfile="{$HOME}/research/sys_info.txt"
outputfile=$HOME/research/sys_info.txt

#if research directory doesn't exist creat it
if [ ! -d $HOME/research ]
then
    mkdir ~/research 2> /dev/null
fi

if [ -f $outputfile ]
then
    rm $outputfile
fi
touch ~/research/sys_info.txt

mkdir ~research 2> /dev/null
touch ~/research/sys_info.txt
outputfile="/home/sysadmin/research/sys_info.txt"

echo "A Quick System Audit Script" >> $outputfile
date >> $outputfile
echo "Machine Type Info:" >> $outputfile
echo $MACHTYPE >> $outputfile
echo -e "The Uname is: $(uname -a) \n" >> $outputfile
echo -e "IP Info: $(ip addr | head -9 |tail -1) \n" >> $outputfile
echo -e "Hostname: $(hostname) \n" >> $outputfile

#command for finding executable files
echo -e "\nExec Files:" >> $outputfile
find /home -type f -perm 777 >> $outputfile

#output for top 10 processes
echo -e "\nTop 10 processes" >> $outputfile
ps aux -m | awk '{print $1, $2, $3, $4, $11}' | head $outputfile


#output the permissions for the shadow and passwd files
files=('/etc/shadow' '/etc/passwd')
for file in ${files[@]};
do
	echo $(ls -l $file) >> $outputfile
done
